### PR TITLE
Remove stretched-link styles and use explicit a hrefs

### PR DESCRIPTION
**Pull request by cmdcolin**
Hi there

Small random PR here, but I found it hard to tell that the "cards" on the website were actually clickable links so I didn't realize that those interactive examples could be navigated. I changed the headers to links so that it is more clear

### CODE REVIEW

**Review by spoenemann — APPROVED** [review]
Cool, thanks!

**Comment by uruuru** [comment]
For some reason this PR didn't show up in my notifications. 

Actually I did the exact opposite change a while ago since I felt it more natural on touch devices to have everything clickable.

**Comment by cmdcolin** [comment]
I am just saying, as a general browser on the website, there was no indication that these "panels" were clickable and could take you to a live demo

**Comment by cmdcolin** [comment]
I don't have that much of an opinion other than that I want other users to be able to easily find the cool demos you guys have made

**Comment by cmdcolin** [comment]
Also as far as I can tell this PR was not deployed to the live website

**Comment by uruuru** [comment]
Maybe I re-add the streched link and preserve the links you introduced - I believe that should be possible. 

Regarding your last comment: there's an issue with deployment, yes. I've let the responsible person know. 

Anyway, thanks for being proactive and providing a PR in the first place :)!

**Pull request merged**
